### ISSUE TITLE
Svm not exists

### ISSUE THREAD

**Issue by xiyanxiyan10** [GokuMohandas/practicalAI#128]
Why it is not contain of svm?

**Comment by GokuMohandas** [comment]
hey @xiyanxiyan10 , I decided not to include it because in many (not all) situations it offers similar performance to random forests. I've also noticed that RFs tend to perform better in multi-class situations whereas SVM outperforms RFs in binary cases. I wanted to cover these basic models quickly and focus on Pytorch/DNN so I decided to skip SVM for now. With that said, the concept behind SVMs is still great to be aware of.
